---
kind: pipeline
type: docker
name: default-build

platform:
  os: linux
  arch: amd64

workspace:
  path: /code

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      filesystem_cache_root: "/var/lib/cache"
      mount:
        - "/code/target"
    volumes:
      - name: cache
        path: /var/lib/cache

  - name: build-contracts
    image: cosmwasm/workspace-optimizer:0.12.8
  - name: full_test
    image: publicawesome/golang:1.18.0-devtooling
    commands:
      - mkdir -p e2e/contracts
      - cp artifacts/*.wasm e2e/contracts/
      - cd e2e/
      - go test . -v
  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    volumes:
      - name: cache
        path: /var/lib/cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      filesystem_cache_root: "/var/lib/cache"
      mount:
        - "/code/target"
volumes:
  - name: cache
    host:
      path: /var/lib/cache

node:
  runner: integration

trigger:
  branch:
    - main
  event:
    - pull_request
    - push
---
kind: signature
hmac: 7bb527353a8987741ae76d01d203ffb8a5dd17e3216a6bda53e7a37add73124e
