---
kind: pipeline
type: docker
name: default-build

workspace:
  path: /code
steps:
  - name: proposal
    image: cosmwasm/workspace-optimizer:0.12.5
trigger:
  branch:
    - main
  event:
    - pull_request
    - push

volumes:
  - name: cache
    temp: {}
node:
  runner: integration
---

