queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>2"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>2"
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: backport to v2
    conditions:
      - base=main
      - label=backport/2.x
    actions:
      backport:
        branches:
          - release/v2.x
  - name: backport to v3
    conditions:
      - base=main
      - label=backport/3.x
    actions:
      backport:
        branches:
          - release/v3.x
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
