queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>2"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>2"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport to v2
    conditions:
      - base=main
      - label=backport/2.x
    actions:
      backport:
        branches:
          - release/v2.x
<<<<<<< HEAD
=======
  - name: backport to v3
    conditions:
      - base=main
      - label=backport/3.x
    actions:
      backport:
        branches:
          - release/v3.x
  - name: automerge to main if approved and labeled
    conditions: []
    actions:
      queue:
>>>>>>> df814cd (ci(mergify): upgrade configuration to current format)
