[package]
name        = "sg-mint-hooks-derive"
version     = "0.1.0"
description = "Macros for generating code used by the `sg-mint-hooks` crate"
authors     = ["Shane Vitarana <s@users.noreply.publicawesome.com>"]
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"
sg-controllers = { workspace = true }
