cd contracts/base-factory && cargo publish && cd ../..
cd contracts/sg721-base && cargo publish && cd ../..
cd contracts/sg721-metadata-onchain && cargo publish && cd ../..
cd contracts/sg721-nt && cargo publish && cd ../..
cd contracts/splits && cargo publish && cd ../..
cd contracts/base-minter && cargo publish && cd ../..
cd contracts/whitelist && cargo publish && cd ../..
cd contracts/vending-factory && cargo publish && cd ../..
cd contracts/vending-minter && cargo publish && cd ../..
cd contracts/whitelist-immutable && cargo publish && cd ../..
