cd packages/sg-std && cargo publish && cd ../..
cd packages/sg721 && cargo publish && cd ../..
cd packages/sg-metadata && cargo publish && cd ../..
cd packages/sg4 && cargo publish && cd ../..
cd packages/sg2 && cargo publish && cd ../..
cd packages/sg-multi-test && cargo publish && cd ../..
cd packages/sg-utils && cargo publish && cd ../..
cd packages/sg1 && cargo publish && cd ../..
cd packages/controllers && cargo publish && cd ../..
cd packages/ethereum-verify && cargo publish && cd ../..
