/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.14.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, InstantiateMsg, MinterParamsForNullable_Empty, Coin, Empty, Sg2QueryMsg } from "./BaseFactory.types";
import "./BaseFactory.client";