/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admin: string;
  airdrop_amount: number;
  airdrop_count_limit: number;
  claim_msg_plaintext: string;
  members: Member[];
  minter_address: string;
  name_collection_address: string;
  name_discount_wl_address: string;
  whitelist_code_id: number;
}
export interface Member {
  address: string;
  mint_count: number;
}
export type ExecuteMsg = {
  register: {
    eth_address: string;
    eth_sig: string;
  };
} | {
  claim_airdrop: {
    eth_address: string;
    eth_sig: string;
  };
};
export type QueryMsg = {
  airdrop_eligible: {
    eth_address: string;
  };
} | {
  get_minter: {};
} | {
  is_registered: {
    eth_address: string;
  };
} | {
  has_claimed: {
    eth_address: string;
  };
} | {
  get_airdrop_count: {};
};
export type Boolean = boolean;
export type Uint32 = number;
export type Addr = string;