/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./BaseFactory.types";
import * as _1 from "./BaseFactory.client";
import * as _2 from "./BaseFactory.message-composer";
import * as _3 from "./BaseMinter.types";
import * as _4 from "./BaseMinter.client";
import * as _5 from "./BaseMinter.message-composer";
import * as _6 from "./Sg721Base.types";
import * as _7 from "./Sg721Base.client";
import * as _8 from "./Sg721Base.message-composer";
import * as _9 from "./Sg721MetadataOnchain.types";
import * as _10 from "./Sg721MetadataOnchain.client";
import * as _11 from "./Sg721MetadataOnchain.message-composer";
import * as _12 from "./Sg721Updatable.types";
import * as _13 from "./Sg721Updatable.client";
import * as _14 from "./Sg721Updatable.message-composer";
import * as _15 from "./Sg721Nt.types";
import * as _16 from "./Sg721Nt.client";
import * as _17 from "./Sg721Nt.message-composer";
import * as _18 from "./Splits.types";
import * as _19 from "./Splits.client";
import * as _20 from "./Splits.message-composer";
import * as _21 from "./VendingFactory.types";
import * as _22 from "./VendingFactory.client";
import * as _23 from "./VendingFactory.message-composer";
import * as _24 from "./VendingMinter.types";
import * as _25 from "./VendingMinter.client";
import * as _26 from "./VendingMinter.message-composer";
import * as _27 from "./VendingMinterWlFlex.types";
import * as _28 from "./VendingMinterWlFlex.client";
import * as _29 from "./VendingMinterWlFlex.message-composer";
import * as _30 from "./WhitelistFlex.types";
import * as _31 from "./WhitelistFlex.client";
import * as _32 from "./WhitelistFlex.message-composer";
export namespace contracts {
  export const BaseFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const BaseMinter = { ..._3,
    ..._4,
    ..._5
  };
  export const Sg721Base = { ..._6,
    ..._7,
    ..._8
  };
  export const Sg721MetadataOnchain = { ..._9,
    ..._10,
    ..._11
  };
  export const Sg721Updatable = { ..._12,
    ..._13,
    ..._14
  };
  export const Sg721Nt = { ..._15,
    ..._16,
    ..._17
  };
  export const Splits = { ..._18,
    ..._19,
    ..._20
  };
  export const VendingFactory = { ..._21,
    ..._22,
    ..._23
  };
  export const VendingMinter = { ..._24,
    ..._25,
    ..._26
  };
  export const VendingMinterWlFlex = { ..._27,
    ..._28,
    ..._29
  };
  export const WhitelistFlex = { ..._30,
    ..._31,
    ..._32
  };
}