/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.14.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./BaseFactory.types";
import * as _1 from "./BaseFactory.client";
import * as _2 from "./BaseFactory.react-query";
import * as _3 from "./BaseMinter.types";
import * as _4 from "./BaseMinter.client";
import * as _5 from "./BaseMinter.react-query";
import * as _6 from "./Sg721Base.types";
import * as _7 from "./Sg721Base.client";
import * as _8 from "./Sg721Base.react-query";
import * as _9 from "./Sg721MetadataOnchain.types";
import * as _10 from "./Sg721MetadataOnchain.client";
import * as _11 from "./Sg721MetadataOnchain.react-query";
import * as _12 from "./Sg721Nt.types";
import * as _13 from "./Sg721Nt.client";
import * as _14 from "./Sg721Nt.react-query";
import * as _15 from "./Splits.types";
import * as _16 from "./Splits.client";
import * as _17 from "./Splits.react-query";
import * as _18 from "./VendingFactory.types";
import * as _19 from "./VendingFactory.client";
import * as _20 from "./VendingFactory.react-query";
import * as _21 from "./VendingMinter.types";
import * as _22 from "./VendingMinter.client";
import * as _23 from "./VendingMinter.react-query";
export namespace contracts {
  export const BaseFactory = { ..._0,
    ..._1,
    ..._2
  };
  export const BaseMinter = { ..._3,
    ..._4,
    ..._5
  };
  export const Sg721Base = { ..._6,
    ..._7,
    ..._8
  };
  export const Sg721MetadataOnchain = { ..._9,
    ..._10,
    ..._11
  };
  export const Sg721Nt = { ..._12,
    ..._13,
    ..._14
  };
  export const Splits = { ..._15,
    ..._16,
    ..._17
  };
  export const VendingFactory = { ..._18,
    ..._19,
    ..._20
  };
  export const VendingMinter = { ..._21,
    ..._22,
    ..._23
  };
}