/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteMsgForNullable_EmptyAndEmpty, Binary, Expiration, Timestamp, Uint64, Decimal, UpdateCollectionInfoMsgForRoyaltyInfoResponse, RoyaltyInfoResponse, MintMsgForNullable_Empty, Empty, InstantiateMsg, CollectionInfoForRoyaltyInfoResponse, QueryMsg } from "./Sg721Updatable.types";