/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Cw4Contract = Addr;
export type Addr = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  group_addr: Cw4Contract;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  distribute: {};
};
export interface InstantiateMsg {
  group_addr: string;
}
export interface ListMembersResponse {
  members: Member[];
}
export interface Member {
  addr: string;
  weight: number;
}
export interface MemberResponse {
  weight?: number | null;
}
export type QueryMsg = {
  config: {};
} | {
  member: {
    address: string;
  };
} | {
  list_members: {
    limit?: number | null;
    start_after?: string | null;
  };
};