/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Group = {
  cw4_instantiate: ContractInstantiateMsg;
} | {
  cw4_address: string;
};
export type Admin = {
  address: {
    addr: string;
  };
} | {
  creator: {};
};
export type Binary = string;
export interface InstantiateMsg {
  group: Group;
}
export interface ContractInstantiateMsg {
  admin?: Admin | null;
  code_id: number;
  label: string;
  msg: Binary;
}
export type ExecuteMsg = {
  distribute: {};
};
export type QueryMsg = {
  group: {};
} | {
  member: {
    address: string;
  };
} | {
  list_members: {
    limit?: number | null;
    start_after?: string | null;
  };
};
export type Addr = string;
export interface MemberListResponse {
  members: Member[];
}
export interface Member {
  addr: string;
  weight: number;
}
export interface MemberResponse {
  weight?: number | null;
}