/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, InstantiateMsg, MinterParamsForParamsExtension, Coin, ParamsExtension, Sg2QueryMsg } from "./VendingFactory.types";